local M = {}

function M.setup()
        
end

function M.install(opts)
        local ensure_installed = {
                "angular",
                "awk",
                "bash",
                "c",
                "c_sharp",
                "cmake",
                "cpp",
                "css",
                "csv",
                "dart",
                "diff",
                "dockerfile",
                "git_config",
                "git_rebase",
                "gitattributes",
                "gitcommit",
                "gitignore",
                "go",
                "gomod",
                "gosum",
                "gotmpl",
                "gowork",
                "hcl",
                "html",
                "http",
                "java",
                "javascript",
                "jsdoc",
                "json",
                "json5",
                "jsonc",
                "ledger",
                "lua",
                "luadoc",
                "luap",
                "luau",
                "make",
                "markdown",
                "markdown_inline",
                "nix",
                "perl",
                "php",
                "php_only",
                "proto",
                "python",
                "query",
                "r",
                "ruby",
                "rust",
                "scala",
                "sql",
                "ssh_config",
                "starlark",
                "terraform",
                "textproto",
                "tmux",
                "toml",
                "tsv",
                "typescript",
                "typespec",
                "yaml",
        }
        vim.cmd([[TSInstall ]] .. table.concat(ensure_installed, " "))
end

return M
